labels:
  env: dev
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/mmcnairy/eks-blueprints-workloads
    targetRevision: main

  # Those default values can be surcharged by Infrastructure as Code
  env: dev
  clusterName: eks-blueprint-cluster # the name of EKS cluster
  blueprint: 'cdk' # cdk | terraform
  karpenterInstanceProfile:
  ingress:
    type: 'alb' # nginx | alb
    host: dev.janus-ai.com # empty or your domain like dev.example.com
